---
name: "Build and Deploy"
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:  # allows manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Homelab
      url: "https://app.cachix.org/deploy/workspace/leo-homelab/"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: leo
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Check
        run: nix flake check
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build
        run: nix build --option sandbox=false --print-build-logs .#cachix-deploy-spec
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
        run: |
          cachix push leo ./result
          cachix deploy activate --async ./result